name: Send a Tweet
on:
  push:
    branches:
      - "main"
    paths:
      - "posts/**/*.md"
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for file in ${{ steps.files.outputs.all }}; do
            echo "${changed_file}"
          done
      # - uses: ethomson/send-tweet-action@v1
